
jwt:
  secret: "ASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDF"

spring:
  application:
    name: jours

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/couplink
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: a
            client-secret: a
            scope:
              - email

          kakao:
            client-name: 'kakao'
            client-id: a
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email

        provider:
          kakao:
            authorization-uri: 'https://kauth.kakao.com/oauth/authorize'
            token-uri: 'https://kauth.kakao.com/oauth/token'
            user-info-uri: 'https://kapi.kakao.com/v2/user/me'
            user-name-attribute: 'id'
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG